const Signal = require("../models/Signal");
const axios = require("axios");

function generateSlug(signal) {
  const coin = signal.symbol.replace("USDT", "").toLowerCase();
  return `${coin}-${signal.interval}-${signal.signal.toLowerCase()}-signal-${Date.now()}`;
}

function generateSEO(signal) {
  const coin = signal.symbol.replace("USDT", "");
  const signalText = signal.signal === "LONG" ? "Long Entry" : "Short Entry";
  
  return {
    title: `${coin} ${signal.interval} ${signalText} Signal - Entry ${signal.entry?.toFixed(2) || signal.price?.toFixed(2)}`,
    description: `Latest ${coin} trading signal (${signal.signal}) on ${signal.interval} timeframe. RSI ${signal.rsi?.toFixed(2)}, Price ${signal.price?.toFixed(2)}. Risk: ${signal.risk}. Auto-generated by LuxAI crypto signal bot.`
  };
}

async function saveSignal(data) {
  try {
    const slug = generateSlug(data);
    const seoData = generateSEO(data);
    
    await Signal.create({
      ...data,
      slug,
      ...seoData
    });
    
    // 🔥 ping Google Search Console
    try {
      const sitemapUrl = encodeURIComponent("https://www.cryptosignal.site/sitemap.xml");
      await axios.get(`https://www.google.com/ping?sitemap=${sitemapUrl}`);
      console.log("✅ Pinged Google for sitemap indexing");
    } catch (e) {
      console.log("⚠️ Ping Google failed:", e.message);
    }
  } catch (err) {
    console.log("DB save error:", err.message);
  }
}

module.exports = { saveSignal };
